[package]
name = "q2-servmon"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
q2-proto = { path = ".." }
clap = { version = "*", features = [ "derive" ] }
ctrlc = { version = "*" }